// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj = require("rescript/lib/js/caml_obj.js");

function print(text) {
  console.log(text);
  
}

function twoNumberSum(intArray, targetNum) {
  return [
          -1,
          11
        ];
}

var testArray = [
  3,
  5,
  -4,
  8,
  11,
  1,
  -1,
  6
];

var doesTestPass = Caml_obj.caml_equal([
      -1,
      11
    ], [
      -1,
      11
    ]);

if (doesTestPass) {
  console.log("test passed");
} else {
  console.log("test failed");
}

var testTarget = 10;

exports.print = print;
exports.twoNumberSum = twoNumberSum;
exports.testTarget = testTarget;
exports.testArray = testArray;
exports.doesTestPass = doesTestPass;
/* doesTestPass Not a pure module */
