// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj = require("rescript/lib/js/caml_obj.js");
var Caml_array = require("rescript/lib/js/caml_array.js");

function print(text) {
  console.log(text);
  
}

function twoNumberSum(intArray, targetNum) {
  var sorted = intArray.sort();
  var arrayLength = sorted.length;
  for(var i = 0; i <= arrayLength; ++i){
    var currentNum = Caml_array.get(sorted, i);
    var potentialMatch = targetNum - currentNum | 0;
    console.log(potentialMatch);
  }
  console.log(sorted);
  return [
          -1,
          11
        ];
}

var testArray = [
  3,
  5,
  -4,
  8,
  11,
  1,
  -1,
  6
];

var doesTestPass = Caml_obj.caml_equal(twoNumberSum(testArray, 10), [
      -1,
      11
    ]);

if (doesTestPass) {
  console.log("test passed");
} else {
  console.log("test failed");
}

var testTarget = 10;

exports.print = print;
exports.twoNumberSum = twoNumberSum;
exports.testTarget = testTarget;
exports.testArray = testArray;
exports.doesTestPass = doesTestPass;
/* doesTestPass Not a pure module */
